[context.production]
  command = "npm run doppler-install && ./doppler run --token $DOPPLER_TOKEN_PRD -- npm run build"

[context.deploy-preview]
  command = "npm run doppler-install && ./doppler run --token $DOPPLER_TOKEN_STG -- npm run build"
